import os
import json
import html

# --------------------------------------------------
# SETTINGS
# --------------------------------------------------

IMAGE_FOLDER = "images"
OUTPUT_FILE = "index.html"

# Supported image types
IMAGE_EXTENSIONS = {
    ".jpg",
    ".jpeg",
    ".png",
    ".webp",
    ".gif"
}


# --------------------------------------------------
# FIND PRODUCTS
# --------------------------------------------------

products = []

for filename in sorted(os.listdir(IMAGE_FOLDER)):

    filepath = os.path.join(IMAGE_FOLDER, filename)

    # Ignore folders
    if not os.path.isfile(filepath):
        continue

    # Check extension
    extension = os.path.splitext(filename)[1].lower()

    if extension not in IMAGE_EXTENSIONS:
        continue

    # Remove extension
    name_without_extension = os.path.splitext(filename)[0]

    # Split filename using _
    parts = name_without_extension.split("_")

    # Last part is price
    if len(parts) >= 2:
        price = parts[-1]
        product_name = " ".join(parts[:-1])
    else:
        price = ""
        product_name = name_without_extension

    products.append({
        "filename": filename,
        "name": product_name,
        "price": price
    })


# --------------------------------------------------
# CONVERT PRODUCT DATA TO JAVASCRIPT
# --------------------------------------------------

products_json = json.dumps(products, ensure_ascii=False)


# --------------------------------------------------
# HTML
# --------------------------------------------------

html_content = f"""<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">

    <meta name="viewport"
          content="width=device-width, initial-scale=1.0">

    <title>My Products</title>

    <style>

        * {{
            box-sizing: border-box;
        }}

        body {{
            margin: 0;
            font-family: Arial, sans-serif;
            background: #f5f5f5;
        }}

        header {{
            background: white;
            padding: 20px;
            text-align: center;
        }}

        h1 {{
            margin: 0;
        }}

        #products {{
            display: grid;
            grid-template-columns:
                repeat(auto-fill, minmax(220px, 1fr));

            gap: 20px;

            padding: 20px;

            max-width: 1400px;

            margin: auto;
        }}

        .product-card {{
            background: white;

            border-radius: 10px;

            overflow: hidden;

            box-shadow:
                0 2px 8px rgba(0,0,0,0.1);
        }}

        .product-card img {{
            width: 100%;

            aspect-ratio: 1 / 1;

            object-fit: cover;

            display: block;
        }}

        .product-info {{
            padding: 15px;
        }}

        .product-name {{
            margin: 0 0 10px;

            font-size: 18px;
        }}

        .product-price {{
            margin: 0;

            font-size: 20px;

            font-weight: bold;

            color: #d35400;
        }}

    </style>

</head>


<body>


<header>

    <h1>My Products</h1>

</header>


<main id="products"></main>


<script>

    // Product information generated by Python
    const products = {products_json};


    const container =
        document.getElementById("products");


    // Create product cards
    products.forEach(product => {{

        const card =
            document.createElement("div");

        card.className =
            "product-card";


        // Image
        const image =
            document.createElement("img");

        image.src =
            "images/" + encodeURIComponent(product.filename);

        image.alt =
            product.name;


        // Information container
        const info =
            document.createElement("div");

        info.className =
            "product-info";


        // Product name
        const name =
            document.createElement("h2");

        name.className =
            "product-name";

        name.textContent =
            product.name;


        // Price
        const price =
            document.createElement("p");

        price.className =
            "product-price";

        price.textContent =
            product.price
                ? "₹" + product.price
                : "Price unavailable";


        // Assemble card
        info.appendChild(name);

        info.appendChild(price);

        card.appendChild(image);

        card.appendChild(info);

        container.appendChild(card);

    }});

</script>


</body>

</html>
"""


# --------------------------------------------------
# WRITE HTML
# --------------------------------------------------

with open(
    OUTPUT_FILE,
    "w",
    encoding="utf-8"
) as file:

    file.write(html_content)


print("HTML generated successfully!")
print("Products found:", len(products))
print("Output:", OUTPUT_FILE)
