
// ============================================================
// PRODUCT DATA GENERATED BY PYTHON
// ============================================================

const PRODUCTS = [{"filename": "bangle_1000.png", "category": "bangle_1000", "serial": "", "price": ""}, {"filename": "necklace_2000.png", "category": "necklace_2000", "serial": "", "price": ""}, {"filename": "necklace_3000.png", "category": "necklace_3000", "serial": "", "price": ""}, {"filename": "set_4000.png", "category": "set_4000", "serial": "", "price": ""}, {"filename": "set_5000.png", "category": "set_5000", "serial": "", "price": ""}, {"filename": "set_7000.png", "category": "set_7000", "serial": "", "price": ""}, {"filename": "set_8000.png", "category": "set_8000", "serial": "", "price": ""}, {"filename": "set_9000.png", "category": "set_9000", "serial": "", "price": ""}];


// ============================================================
// SELLER WHATSAPP
// ============================================================

const SELLER_WHATSAPP =
    "918902411270";


// ============================================================
// ELEMENTS
// ============================================================

const productsGrid =
    document.getElementById("products-grid");

const modal =
    document.getElementById("buyModal");

const modalClose =
    document.getElementById("modalClose");

const modalOverlay =
    document.querySelector(".modal-overlay");

const orderForm =
    document.getElementById("orderForm");

const selectedProduct =
    document.getElementById("selectedProduct");


// Currently selected product

let selectedProductData = null;


// ============================================================
// CREATE PRODUCT CARDS
// ============================================================

function displayProducts() {

    productsGrid.innerHTML = "";


    if (PRODUCTS.length === 0) {

        productsGrid.innerHTML = `
            <p style="
                grid-column: 1 / -1;
                text-align: center;
                padding: 50px;
                color: #777;
            ">
                No jewellery products available.
            </p>
        `;

        return;
    }


    PRODUCTS.forEach(product => {

        const card =
            document.createElement("article");

        card.className =
            "product-card";


        // ----------------------------------------------------
        // IMAGE
        // ----------------------------------------------------

        const imageWrap =
            document.createElement("div");

        imageWrap.className =
            "product-image-wrap";


        const image =
            document.createElement("img");

        image.className =
            "product-image";

        image.src =
            "images/" +
            encodeURIComponent(
                product.filename
            );

        image.alt =
            product.category;

        image.loading =
            "lazy";


        const overlay =
            document.createElement("div");

        overlay.className =
            "image-overlay";


        imageWrap.appendChild(image);

        imageWrap.appendChild(overlay);


        // ----------------------------------------------------
        // DETAILS
        // ----------------------------------------------------

        const details =
            document.createElement("div");

        details.className =
            "product-details";


        const category =
            document.createElement("h3");

        category.className =
            "product-category";

        category.textContent =
            product.category;


        const serial =
            document.createElement("p");

        serial.className =
            "product-serial";

        serial.textContent =
            "Product No. " +
            product.serial;


        const price =
            document.createElement("p");

        price.className =
            "product-price";

        price.textContent =
            product.price
                ? "MRP ₹" + product.price
                : "Price on request";


        const buyButton =
            document.createElement("button");

        buyButton.className =
            "buy-button";

        buyButton.type =
            "button";

        buyButton.textContent =
            "Buy This Jewellery";


        buyButton.addEventListener(
            "click",
            () => openBuyModal(product)
        );


        details.appendChild(category);

        details.appendChild(serial);

        details.appendChild(price);

        details.appendChild(buyButton);


        card.appendChild(imageWrap);

        card.appendChild(details);

        productsGrid.appendChild(card);

    });
}


// ============================================================
// OPEN BUY MODAL
// ============================================================

function openBuyModal(product) {

    selectedProductData =
        product;


    selectedProduct.innerHTML = `
        <strong>
            ${escapeHtml(product.category)}
        </strong>

        <span>
            Product No. ${escapeHtml(product.serial)}
            &nbsp; • &nbsp;
            MRP ₹${escapeHtml(product.price)}
        </span>
    `;


    orderForm.reset();


    modal.classList.add("active");

    modal.setAttribute(
        "aria-hidden",
        "false"
    );


    document.body.style.overflow =
        "hidden";


    setTimeout(() => {

        document
            .getElementById("customerName")
            .focus();

    }, 100);
}


// ============================================================
// CLOSE MODAL
// ============================================================

function closeModal() {

    modal.classList.remove("active");

    modal.setAttribute(
        "aria-hidden",
        "true"
    );


    document.body.style.overflow =
        "";
}


modalClose.addEventListener(
    "click",
    closeModal
);


modalOverlay.addEventListener(
    "click",
    closeModal
);


document.addEventListener(
    "keydown",
    event => {

        if (
            event.key === "Escape" &&
            modal.classList.contains("active")
        ) {

            closeModal();
        }
    }
);


// ============================================================
// SUBMIT ORDER
// ============================================================

orderForm.addEventListener(
    "submit",
    function(event) {

        event.preventDefault();


        if (!selectedProductData) {
            return;
        }


        const customerName =
            document
                .getElementById("customerName")
                .value
                .trim();


        const customerNumber =
            document
                .getElementById("customerNumber")
                .value
                .trim();


        const deliveryAddress =
            document
                .getElementById("deliveryAddress")
                .value
                .trim();


        // ----------------------------------------------------
        // Basic validation
        // ----------------------------------------------------

        if (
            customerName === "" ||
            customerNumber === "" ||
            deliveryAddress === ""
        ) {

            alert(
                "Please complete all the required fields."
            );

            return;
        }


        const cleanedNumber =
            customerNumber.replace(
                /[^0-9+]/g,
                ""
            );


        if (cleanedNumber.length < 8) {

            alert(
                "Please enter a valid WhatsApp/mobile number."
            );

            return;
        }


        // ----------------------------------------------------
        // CUSTOM MESSAGE
        // ----------------------------------------------------

        const message =

            "I, " +

            customerName +

            ", wish to buy the Jewellery Product No. " +

            selectedProductData.category +

            " " +

            selectedProductData.serial +

            " MRP Price ₹" +

            selectedProductData.price +

            ". Kindly deliver the package to my delivery address " +

            deliveryAddress +

            ". For the same pls provide me your QR code scanner for payment";


        // ----------------------------------------------------
        // WHATSAPP URL
        // ----------------------------------------------------

        const whatsappURL =

            "https://wa.me/" +

            SELLER_WHATSAPP +

            "?text=" +

            encodeURIComponent(message);


        // ----------------------------------------------------
        // Close modal first
        // ----------------------------------------------------

        closeModal();


        // ----------------------------------------------------
        // Tell customer what is happening
        // ----------------------------------------------------

        alert(
            "Your custom WhatsApp message is ready.\\n\\n" +

            "Please allow popups if your browser asks.\\n\\n" +

            "WhatsApp will now open with your purchase " +
            "message addressed to the seller. " +

            "Please review the message and press Send."
        );


        // ----------------------------------------------------
        // Open WhatsApp
        // ----------------------------------------------------

        const whatsappWindow =
            window.open(
                whatsappURL,
                "_blank"
            );


        // ----------------------------------------------------
        // Popup blocked
        // ----------------------------------------------------

        if (!whatsappWindow) {

            alert(
                "The browser blocked the WhatsApp popup.\\n\\n" +

                "Please allow popups for this website " +
                "and click the Buy button again."
            );
        }

    }
);


// ============================================================
// HTML ESCAPING
// ============================================================

function escapeHtml(value) {

    return String(value)
        .replace(/&/g, "&amp;")
        .replace(/</g, "&lt;")
        .replace(/>/g, "&gt;")
        .replace(/"/g, "&quot;")
        .replace(/'/g, "&#039;");
}


// ============================================================
// START
// ============================================================

displayProducts();
